- .circleci/config.yml
- Cargo.toml
- README.md
- src/client/consumer.rs
- src/client/mod.rs
- src/client/producer.rs
- src/connection.rs
- src/connection/transport.rs
- tests/client.rs
- tests/consumer.rs
- tests/producer.rs
This is really handy if you wanna debug interactions with cluster running in K8s. Now you just need the [kubectl SOCKS5 plugin](https://github.com/yokawasa/kubectl-plugin-socks5-proxy) and it "just works".
Since adding yet another connect method didn't feel right, I've moved the client creation over to a builder pattern and to proof that it is nice and modular, I've made TLS optional (which some OSS users might welcome).
> feat: SOCK5 support

- src/protocol/primitives.rs
- tests/client.rs
> fix: do not fail when record batches are cut off in  `FetchResponse`

- src/connection.rs
- src/connection/topology.rs
Connects to #49, in that it adds a tiny bit of testing around getting a new arbitrary broker connection to cache.
This also adds a bit of type info around different sources of broker connection, and fixes a subtle bug where broker id was being logged as `None` even though we had a broker ID from the topology.
Again recommended to review commit-by-commit.
I feel less confident about the value of these extractions and the new test. If the new test fails, it's likely to be a flaky failure too because of the randomness.
Looking at other code like the controller and partition leader caching, I think perhaps the broker caching trait could be reused, and then perhaps the `maybe_retry` functions could be shared more and tested more? Not sure yet though.
> refactor: Add a little testability, abstract a bit over broker kinds

- src/backoff.rs
- src/client/controller.rs
- src/client/partition.rs
- src/connection.rs
I think this was always meant to be this way because the request name is
passed as an argument, but this got somehow mixed up in the meantime and
now we don't probably report non-fatal errors anymore. To prevent this
in the future this tightens the type bounds a bit.
> fix: `retry_with_backup` takes error for "continue"

- rust-toolchain.toml
Update to the latest rust.
:wave: @jdstrand 
---
* build: use rust 1.58.1 (e2dff26)
Security bugfix release, see:
https://groups.google.com/g/rustlang-security-announcements/c/R1fZFDhnJVQ?pli=1
> build: use rust  1.58.1

- .circleci/config.yml
- Cargo.toml
We already test that `--all-features` builds in CI, so we can also
publish feature-complete docs.
> chore: build docs with `--all-features`

- .circleci/config.yml
- .gitignore
- Cargo.toml
- README.md
- benches/write_throughput.rs
- src/protocol/record.rs
```text
sequential/rskafka      time:   [288.29 us 298.38 us 308.18 us]
change: [-35.194% -30.910% -26.110%] (p = 0.00 < 0.05)
Performance has improved.
parallel/rskafka        time:   [15.793 us 16.002 us 16.193 us]
change: [-51.655% -49.590% -48.139%] (p = 0.00 < 0.05)
Performance has improved.
```
> feat: benchmark + fix CRC performance

- .circleci/config.yml
- Cargo.toml
- README.md
- benches/write_throughput.rs
- src/client/partition.rs
- src/client/producer.rs
- src/protocol/record.rs
- tests/client.rs
- tests/consumer.rs
- tests/produce_consume.rs
- tests/rdkafka_helper.rs
- tests/test_helpers.rs
While we technically don't want to emit compressed data for IOx, I'm worried that some backup / cluster tool will compress our messages anyways and we end up in some incident not being able to read the data any longer.
The primary contribution of this PR is to figure out how compression works. Adding more types can be done later and should be rather easy, since they all follow the same pattern (i.e. a compressed block that follows the number of records).
> feat: support gzip compression

- .gitignore
- Cargo.toml
- README.md
- src/client/partition.rs
- src/protocol/record.rs
- src/protocol/vec_builder.rs
- tests/produce_consume.rs
- tests/rdkafka_helper.rs
Snappy is a bit more messy than the other formats, but that's what IOx currently writes via rdkafka. Implementing this allows a slightly smoother transition since we don't need to drain the compressed data from our active Kafka clusters.
> feat: support Snappy (de)compression

- README.md
- benches/write_throughput.rs
- src/client/consumer.rs
- src/client/producer.rs
- src/client/producer/aggregator.rs
- src/protocol/record.rs
- src/record.rs
- tests/client.rs
- tests/produce_consume.rs
- tests/rdkafka_helper.rs
- tests/test_helpers.rs
In the NULL case (which can be produced by rdkafka) the length of these
fields is set to -1.
> fix: record key/value can be NULL

- src/client/consumer.rs
- src/client/partition.rs
- tests/client.rs
- tests/consumer.rs
If we encounter `OffsetOutOfRange` this means that the start offset of
the stream lies outside of the range that Kafka knows. In this case we
should not hot-loop and try to poll new data forever, since this is very
likely NOT intended.
The only use case I could come up with is to start a stream at some "yet
to be produced" offset, but I fail to come up with a practical reasoning
behind this as well as a method to dermine the start offset for such a
use case.
So most users are likely interested to subscribe to data that already
exists within the system.
> fix: terminate consumer stream on `OffsetOutOfRange`

- .circleci/config.yml
- README.md
- src/client/error.rs
- src/client/partition.rs
- src/protocol/messages/delete_records.rs
- src/protocol/messages/mod.rs
- tests/client.rs
We don't need record deletion in production, but having this operation available helps us to understand how Kafka behaves when data is truncated due to retention policies.
> feat: implement record deletion

- src/client/partition.rs
- tests/client.rs
Kafka may always return entire record batches even though our request offset is "in the middle" of it. So we need to filter out records that that a lower than our minimal offset.
> fix: filter out records that we've not requested

- src/client/partition.rs
- src/protocol/messages/list_offsets.rs
- tests/client.rs
> feat: extend watermark API to get both low/high offset

- clippy.toml
- src/client/consumer.rs
- src/client/producer.rs
- src/client/producer/broadcast.rs
Tokio might preempt tasks at any point so `now_or_never` might return
`None`. See https://tokio.rs/blog/2020-04-preemption
We could try to workaround this by using data structures from `futures`
instead of `tokio` which to not hook into the tokio cooperative
scheduling. However this has certain drawbacks
- The cooperative scheduling in tokio is actually not that bad, so we
should rather work with it instead of against it.
- The assumption that `futures` data structures don't participate in
cooperative scheduling is only because currently they cannot interact
with the runtime in any way. This might change when Rust's async
ecosystem evolves so it kinda seems like a non-future-proof
workaround.
Fixes #102.
While I'm on it I also disallowed async `read` because it has the same issue as the …
> fix: disallow now_or_never  (and async `read`)

- src/client/consumer.rs
- tests/client.rs
- tests/consumer.rs
- tests/produce_consume.rs
- tests/producer.rs
- tests/test_helpers.rs
This is required to provide a race-free way to start at the earliest or
latest offset, because fetching the offset and then creating a stream
might fail because in the meantime the Kafka retention policy might
already have removed the offsets in question.
> feat: allow `StreamConsumer` to start at "earliest"/"latest" offset

- src/client/partition.rs
This keeps consumer streams from dying when the Kafka cluster is in flux
(e.g. when Strimzi restarts brokers).
Fixes #84.
> fix: ignore `InvalidReplicationFactor`

- fuzz/fuzz_targets/protocol_reader.rs
- src/messenger.rs
- src/protocol/messages/api_versions.rs
- src/protocol/messages/header.rs
- src/protocol/primitives.rs
This avoids that we write partial messages to the underlying TCP/TLS
connection and mess up message framing. This will nearly always lead to
broker-side errors and the broker closes the connection.
Fixes #103.
> fix: make `Messenger::request` cancellation-safe

- src/protocol/frame.rs
This is part of https://github.com/influxdata/rskafka/issues/101.
> fix: Use a `try_from` instead of a cast

- src/protocol/primitives.rs
> fix: Remove `as` conversions in protocol/primitives.rs

- src/protocol/record.rs
> fix: Remove `as` conversions in protocol/record.rs

- .circleci/config.yml
- src/connection.rs
- tests/client.rs
Some parts of the code were referencing types behind feature flags, and CI wasn't catching it - this PR corrects both.
---
* fix: missing TLS feature gates (1c0eb13)
Adds missing cfg(tls) annotations to code blocks that require it, allowing
cargo check --all-targets to pass.
* ci: check all targets with no features (04f6863)
Adds --all-targets to the "no default features" build, which causes it to
validate the flags used in #[cfg(test)] gated blocks too.
> fix: TLS feature flag

- .github/semantic.yml
The external bot was replaced by a GitHub action in #127.
> chore: remove obsolete semantic config file

- .circleci/config.yml
- README.md
- benches/write_throughput.rs
- docker-compose-kafka.yml
- docker-compose-redpanda.yml
- tests/client.rs
- tests/consumer.rs
- tests/java_helper.rs
- tests/produce_consume.rs
- tests/producer.rs
- tests/rdkafka_helper.rs
- tests/test_helpers.rs
> test: SOCKS5 in CI and docker compose files

- .circleci/config.yml
- docker-compose-redpanda.yml
- src/client/partition.rs
- tests/client.rs
Newer versions of Redpanda do not require the `OffsetOutOfBounds`
quirk anymore, so let's remove it. See #147 on why this is a good idea.
> fix: remove potentially buggy Redpanda quirk

- src/protocol/messages/create_topics.rs
- src/protocol/primitives.rs
Compact array representations were introduced at the same time as
compact strings and tagged fields. For arrays with versioned structures
we already use these. For primitive arrays however we did not use them
yet. The only message where this applies is CreateTopics and the broker
didn't seem to care that we've messed up the serialization of this one
field.
Compact arrays might be helpful for other message types as well, so this
is both a fix and some feature work.
> fix: use compact arrays where needed

- src/messenger.rs
```console
$ env TEST_INTEGRATION=1 KAFKA_CONNECT=localhost:9010 cargo bench --all-features --bench throughput
...
read/rskafka            time:   [7.1591 us 7.2529 us 7.3444 us]
change: [-33.377% -22.989% -10.606%] (p = 0.00 < 0.05)
Performance has improved.
Found 2 outliers among 15 measurements (13.33%)
1 (6.67%) high mild
1 (6.67%) high severe
...
write_sequential/rskafka
time:   [335.19 us 347.14 us 366.57 us]
change: [-6.1186% +1.7049% +11.034%] (p = 0.71 > 0.05)
No change in performance detected.
...
write_parallel/rskafka  time:   [15.904 us 16.063 us 16.261 us]
change: [-4.8534% -2.3144% +1.2491%] (p = 0.16 > 0.05)
No change in performance detected.
Found 1 outliers among 15 measurements (6.67%)
1 (6.67%) high severe
````
The problem with spawning tasks (or a MPSC construction) …
> refactor: speed up IO

- src/client/error.rs
- src/connection.rs
- src/connection/transport.rs
- src/messenger.rs
- src/protocol/error.rs
- src/protocol/frame.rs
- src/protocol/messages/mod.rs
- src/protocol/traits.rs
This makes it easier to add new error variants later w/o introducing
breaking changes.
> refactor: make errors non-exhaustive

- Cargo.toml
- benches/throughput.rs
- tests/java_helper.rs
- tests/test_helpers.rs
Use a maintained fork for `dotenv`.
> chore: `dotenv` -> `dotenvy`

- src/client/producer.rs
Marks the `ProducerClient` as pub, so external code can inject instrumentation over the kafka client via decorators when constructing the `BatchProducer`.
This allows:
* Recording the latency of the low-level produce call independent of the aggregation logic (just the serialisation / protocol overhead / network I/O / etc)
* Inspecting the `Record` payloads on the producer side (somewhat related to https://github.com/influxdata/influxdb_iox/issues/5117)
* Emitting metrics for `produce()` errors, etc
This is not a breaking API change.
---
* feat: pub ProducerClient for instrumentation hook (9bf370a)
This commit changes the visibility of the ProducerClient abstraction and the
associated BatchProducer constructor method (used internally to swap out the
real client impl with a mock for testing …
> feat: pub ProducerClient for instrumentation hook

- src/client/controller.rs
- src/client/metadata_cache.rs
- src/client/mod.rs
- src/client/partition.rs
- src/connection.rs
- src/protocol/messages/metadata.rs
- src/protocol/primitives.rs
This PR halves the number of requests needed by the `PartitionClient` for leadership discovery in the common/happy path.
Ideally we would perform a metadata request, and then use that to initialise all the `PartitionClient` a user needs in one go and hand them to the user - however because a `PartitionClient` is lazily initialised by a call to [`Client::partition_client()`] at any point in time, it is not possible to perform batch initialisation in this way (but is a slightly nicer UX).
Instead the approach this PR takes is to maintain a metadata cache (invalidated & updated automatically as a side effect of normal usage) and use the cached metadata to optimistically select a partition's leader. This is then validated by contacting the potential leader to assert it indeed is the actual …
> feat: metadata cache for leader discovery

- benches/throughput.rs
- src/client/mod.rs
- src/client/partition.rs
- tests/client.rs
- tests/consumer.rs
- tests/produce_consume.rs
- tests/producer.rs
This exposes a method that can be used to drive leader discovery _before_ the first call to `produce()` on a `PartitionClient`. This allows us to "pre-warm" the cached broker connection to the leader and avoid doing it when we send through the first write.
Ideally we would do this automatically when initialising the `PartitionClient`, but that would be a breaking change  as [the constructor](https://github.com/influxdata/rskafka/blob/b612f08cefe92c26d54db61044d219d994e671e6/src/client/mod.rs#L119-L129) would need to become async - happy to change it if a breaking change is acceptable :+1:
I wasn't really sure how to test this :shrug:
---
* feat: support pre-warming PartitionClient (b612f08)
Adds a refresh_leader() method to force the PartitionClient through the 
discovery process.
This …
> feat: support pre-warming PartitionClient

- src/client/partition.rs
Changes the func called in the pre-warm step introduced in #165 - `get_leader()` discovers the leader, but only `get()` caches the connection!
Doh!
---
* fix: pre-warm cache broker connections (64211b5)
PR #165 added leader discovery at initialisation time and intended to also
cache the broker connection but called the wrong func.
This commit calls get() which establishes & caches the broker connection.
> fix: pre-warm cache broker connections

- Cargo.toml
- src/client/producer.rs
Inspired by https://github.com/influxdata/influxdb_iox/pull/5400.
> chore: fix `cargo bench -- --save-baseline`

- .circleci/config.yml
- README.md
- benches/throughput.rs
- docker-compose-kafka.yml
- docker-compose-redpanda.yml
- src/client/consumer.rs
- src/client/error.rs
- src/client/mod.rs
- src/client/partition.rs
- src/client/producer.rs
- src/messenger.rs
- tests/client.rs
- tests/consumer.rs
- tests/produce_consume.rs
- tests/producer.rs
Redpanda seems to expect that we send a bit more data in the protocol header (kafka doesn't care), so let's make it happy.
Topic auto-creation should never have worked for our dev/ci Kafka/redpanda nodes. Let's disable it (this actually was caught by the test for the bind mode feature, see next point).
Let's face it: the protocol is a bit of a mess and some users (mostly
the ones that expect that partitions can be deleted) need to deal with
it, while for others we can make iron over it.
Closes #168.
Fixes #169.
> fix: update redpanda, fix issues

- .circleci/config.yml
- README.md
- tests/client.rs
- tests/consumer.rs
- tests/produce_consume.rs
- tests/producer.rs
- tests/test_helpers.rs
Instead of having X different macros and control flow exists, let's have
one mechanism to read env variables and decide if a test shall run or
not.
This also moves the "which broker implementation supports which features"
from a bunch of environment variables into a nice enum. This will
greatly help when we expand the set of admit APIs, see #157 for example.
> test: improve testing config

- Cargo.toml
- README.md
- benches/throughput.rs
- src/client/consumer.rs
- src/client/partition.rs
- src/client/producer.rs
- src/client/producer/aggregator.rs
- src/lib.rs
- src/record.rs
- tests/client.rs
- tests/java_helper.rs
- tests/produce_consume.rs
- tests/rdkafka_helper.rs
- tests/test_helpers.rs
Looking at IOx, we currently have 3 time-like dependencies:
- time 0.1: this is a backwards-compat dependencies of chrono 0.4 and
will be removed in chrono 0.5
- time 0.3: only used by rskafka
- chrono 0.4: used by everything else
Let's remove time 0.3 from that list. Also it seems that chrono gains
more traction recently, so IMHO it's the safer bet.
Also see #144.
> refactor: replace `time` w/ `chono`

- .circleci/config.yml
CircleCI phases out the currently used mechanism, so we need to migrate it to use project-wide triggers.
> ci: update fuzz job scheduling

- fuzz/fuzz_targets/protocol_reader.rs
- src/connection.rs
- src/messenger.rs
Small clean-up before I start to work on #182.
> refactor: remove interior mutable from `Messenger::version_ranges`

- src/backoff.rs
- src/client/controller.rs
- src/client/partition.rs
- src/connection.rs
- src/lib.rs
- src/messenger.rs
- src/throttle.rs
> feat: respect throttling

- src/client/controller.rs
- src/client/metadata_cache.rs
- src/client/partition.rs
- src/connection.rs
This is helpful when you want to understand certain issues from logs.
> feat: log reason about WHY we invalidate caches

- src/client/controller.rs
- src/client/metadata_cache.rs
- src/client/mod.rs
- src/client/partition.rs
- src/connection.rs
Under certain conditions it MAY happen that metadata cache invalidation races, e.g.:
| Thread 1     | Thread 2     |
| ------------ | ------------ |
| get metadata |              |
|              | get metadata |
| invalidate   |              |
| get metadata |              |
|              | invalidate   |
Here the 2nd invalidation is unnecessary. It's not a correctness issue, but we throw away cached data that is perfectly fine.
To work around this, we now track a "generation" for data that we get from the metadata cache and check this during invalidation requests.
Ref #62. (not closing, need to do the same for the broker connection cache)
> fix: (potential) metadata cache invalidation race

- src/backoff.rs
- src/client/controller.rs
- src/client/partition.rs
- src/connection.rs
- src/throttle.rs
> fix: (potential) broker cache invalidation race

- src/client/controller.rs
- src/protocol/messages/delete_topics.rs
- src/protocol/messages/mod.rs
- tests/client.rs
> feat: implement topic deletion

- src/backoff.rs
- src/client/controller.rs
- src/client/mod.rs
- src/client/partition.rs
- src/connection.rs
- src/lib.rs
Describe your proposed changes here.
This changes will allow users to configure backoff/retry to their liking. This is also one of a 2 part changes (other still in progress) in an attempt to also allow a form of termination and not try forever especially without informing the user of the progress.
> refactor: Clientbuilder accept backoffconfig

- src/backoff.rs
- src/connection.rs
- src/lib.rs
- tests/client.rs
Closes #212
Describe your proposed changes here.
This PR implements a termination point for retry with backoff.
> feat: retry with deadlinea

- Cargo.toml
- rust-toolchain.toml
- src/client/consumer.rs
- src/client/partition.rs
- src/connection/transport.rs
- src/protocol/record.rs
- tests/client.rs
Requires for our CI because `cargo-fuzz` no longer builds with this old version.
> chore: upgrade to Rust 1.72

- src/backoff.rs
- src/connection.rs
- src/lib.rs
- tests/client.rs
This PR makes a few small changes:
- Changes the derived display impl of `BackoffError` to also include the `source` error.
- Removes a few unhelpful TODO's, which are no longer correct.
- Exposes `connection::Error` as `ConnectionError`. Currently it is not visible at all, since `connection` is a private module.
- Captures errors from broker connection and passes that along too.
Nothing should be breaking or particularly intrusive.
> feat: Minor improvements to error visibility

- deny.toml
> chore: fix cargo deny configs

- Cargo.toml
- rust-toolchain.toml
- src/client/controller.rs
- src/client/partition.rs
- src/connection.rs
- src/protocol/frame.rs
- tests/java_helper.rs
- tests/test_helpers.rs
- update MSRV
- drop `once_lock`
- drop `async_trait`
> chore: rust 1.80

- Cargo.toml
- benches/throughput.rs
- fuzz/fuzz_targets/protocol_reader.rs
- src/client/consumer.rs
- src/connection/transport.rs
Actually we don't need this, all our nested types fall roughly into three categories:
- **no perf critical:** Use `Box::pin` to create a new allocation `Pin<Box<T>>`
- **already alloated:** They where already wrapped in a `Box<T>` (e.g. for enums with vastly different variants), so `Pin<Box<T>>` is the same overhead.
- **`Unpin`:** Some upstream types implement `Unpin`, so you can just use `Pin::new(&mut x)`.
> chore: drop `pin-project-lite`

- Cargo.toml
- src/client/mod.rs
- src/connection.rs
- src/connection/transport.rs
- src/connection/transport/sasl.rs
- src/messenger.rs
- tests/client.rs
- tests/produce_consume.rs
#239
support SASL SCRAM-SHA-256 and SCRAM-SHA-512
> feat: support SASL SCRAM mechanism

- src/client/consumer.rs
- src/client/partition.rs
- tests/consumer.rs
This commit allow timestamp query for partition offset. As stated in the doc comment of `OffsetAt`, timestamp-based query is inconsistent, but I think it better to let the users make their own choice instead of total removal of this sometimes useful feature. I add a feature gate to  disable timestamp-based query for offset by default, only those actively looking for timestamp-based query would enable this feature.
> feat: add `timestamp-query` feature to allow timestamp offset query

- .circleci/config.yml
This is already part of the CI image.
> chore: do not reinstall cargo deny in CI

- Cargo.toml
- src/client/mod.rs
- src/connection.rs
- src/connection/transport.rs
- src/connection/transport/sasl.rs
- src/lib.rs
- src/messenger.rs
- src/protocol/frame.rs
Closes #252.
This adds `SASL/OAUTHBEARER` support to the client.
Since `SaslConfig` no longer always contains `Credentials` I did some minor refactoring and moved the rsasl `SASLConfig` building into a separate method on `SaslConfig`. There is no convenient method for doing Oauth, so we have to implement an rsasl callback for providing a bearer token.
I've chosen the token callback to be asynchronous, since users of this library are likely to use an asynchronous HTTP library, or other OAUTH mechanism, and mixing sync and async is a very bad idea.
One thing I have not done is write any tests, mostly since writing an actual integration test supporting this would be very complicated. Since I have now done some of that myself I have a vague idea of what would be needed:
- You would need an …
> feat: Add SASL/OAUTHTOKEN support

- .circleci/config.yml
- docker-compose-kafka.yml
- src/messenger.rs
- tests/client.rs
The previous fix did not work. This is now definitely verified to be working and also makes coherent sense.
I made a fix in the OAUTHBEARER PR to fix the SASL flow to send a message even when the final state was `Finished(true)`. My solution instead broke the flow in a _different_ way, making it so that we send the final message twice.
This should  fix it. I didn't catch it before because my kafka configuration was wrong and didn't properly require plain auth, and this particular issue doesn't affect oauthbearer. This time I've verified that it fails with `InvalidSaslState` without this fix, and manages to connect with it.
> fix: SASL/PLAIN

- src/client/mod.rs
- src/connection.rs
- src/connection/transport.rs
- src/lib.rs
Closes #268
Add support for setting a connection timeout for establishing TCP connections. Having the option for a timeout here is good to prevent the client from getting stuck if some weird network errors happen while connecting, which we've seen a few times.
I had to allow the clippy too-many-arguments lint on two internal methods since we need to pass the timeout parameter down the stack. Fixing this would take a larger refactor than I think is appropriate for this change.
The default value is set to 30 seconds as suggested.
I tried to write a more meaningful test, but ended up with one that just times out instantly. It's hard to create a test for this since connecting to an actually closed port will just produce "Connection refused", and relying on a connection being "slow" is almost …
> feat: connection timeout
